baseURL = "https://blog.ellenlangelaar.nl"
languageCode = "en-us"
title = "Coding Blog"
theme = "codeblog"
googleAnalytics = "UA-37182945-5"
copyright = "&copy; <a href='https://ellenlangelaar.nl'>Ellen Langelaar</a> 2018"

[params.social]
github = "e11en"
